#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '👷 Styling, Testing and Building your project before committing...'

# Check Prettier standards
yarn format-prettier && yarn check-prettier ||
(
  echo '❌ Prettier Check Failed.
    Run yarn format-prettier, add changes and try commit again.';
  false;
)

# Check ESLint Standards
yarn lint-staged ||
(
  echo '❌ ESLint Check Failed.
    Make the required changes listed above, add changes and try to commit again.'
  false;
)


# Check tsconfig standards
yarn check-types ||
(
  echo '❌ Type Check Failed.
    Make the changes required above.'
  false;
)


# If everything passes... Now we can commit
echo '👷 Trying to build now...'

yarn build ||
(
  echo '❌ Build Failed.
    View the errors above to see why.'
  false;
)

# If everything passes... Now we can commit
echo '✅ Built Succesfully. Committing...'
